Added option to start with the mouse hidden
Airblader/unclutter-xfixes pull request #59
Opened 2020-09-13 20:07 UTC by sqrtroot

Small new feature, I needed this for a project.
The mouse starts hidden, instead of showing. Removing the need to wait at least one timeout period. The option is behind a CLI flag as to not change the default behaviour.

2020-09-13 20:10 UTC, sqrtroot commented
Build seems to fail on making the docs? Building docs works locally.

2020-09-15 08:00 UTC, Airblader requested changes
Thanks for the PR! I left a few comments, would be great if you could address those.

2020-09-28 07:28 UTC, sqrtroot commented on src/unclutter.c
> +    if(config.start_hidden)
Ah I think the name confused me, I've moved it to run as that seems the next logical place to me

2020-10-06 06:52 UTC, Airblader requested changes
Thanks! The code looks good now. Can you please squash the commits into one and force-push again? Then just drop a comment and we're good to go.

2020-10-22 11:29 UTC, sqrtroot commented
Any progress on this?

2020-10-22 11:36 UTC, Airblader approved these changes
Sorry, I don't get notifications for pushes, only comments. All good now, thank you!

2020-10-22 11:36 UTC, merged