Add --no-timeout
Airblader/unclutter-xfixes pull request #83
Opened 2023-07-19 12:02 UTC by Papierkorb

Hello!

I recently found this tool to hide the mouse cursor if I'm using my notebooks touch screen.  And it works great!

However, my small gripe is that I need to set a timeout for the cursor to be hidden anyway.   Thus, I've added the `--no-timeout` option which allows the user to disable the timeout functionality entirely.

The defaults are unchanged, so existing users shouldn't notice much difference to their work flows :)

Cheers!

2023-07-23 17:42 UTC, Airblader requested changes
Thanks for the PR! I just have two minor style nitpicks. Could you please take care of them & ideally squash the commits? Thanks so much!

Please do drop a comment when you're done so I get notified.

2023-07-23 17:42 UTC, Airblader commented on src/event.c
> +    if (config.timeout >= 0.0) event_init_timer();
nit: could we please put this on a separate line and use braces?

2023-07-23 17:42 UTC, Airblader commented on src/event.c
> +        if (idle_watcher) ev_timer_again(loop, idle_watcher);
nit: could we please put this on a separate line and use braces?

2023-07-24 08:26 UTC, Papierkorb commented
Pushed with the requested changes

2023-07-24 08:55 UTC, Airblader approved these changes
Awesome, thanks!

2023-07-24 08:55 UTC, merged